[package]
name = "csv_read_bin"
version = "0.1.0"
authors = ["am009 <634960348@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"