[package]
name = "user_lib"
version = "0.1.0"
authors = ["am009 <634960348@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy_system_allocator = "0.3.9"